### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by h-ucchi** [h-ucchi/furima-37078#22]
- 自身のフリマアプリのURL
- Basic認証のIDとパスワード
  - ID：admin
  - Pass：2222
- 出品者用のメールアドレスとパスワード
  - メールアドレス：aaa@aaa
  - Pass：aaaaaa00
- 購入者用のメールアドレスとパスワード
  - メールアドレス：bbb@bbb
  - Pass：bbbbbb00

**Comment by yusuketono** [comment]
@h-ucchi ご提出ありがとうございます‼︎
フリマアプリのURLが記載がないようです。
お手数ですが、フリマアプリのURLの記載をお願いします。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by h-ucchi** [comment]
フリマアプリのリンクは以下の通りです
https://furima-37078.herokuapp.com/

ご確認いただけますと幸いです。
よろしくお願いいたします。

**Comment by yusuketono** [comment]
@h-ucchi さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**


![最終課題終了_おめでとう画像1](https://user-images.githubusercontent.com/51428519/159389747-b597c037-ba8b-4874-9b5a-9c6c10de7466.png)

**Comment by h-ucchi** [comment]
ご確認ありがとうございます！

イシュークローズさせていただきます１
